package receipt

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"

	"github.com/bishal-dd/receipt-generator-backend/graph/model"
)

type ReceiptResolver struct{}

func (r *ReceiptResolver) Receipts(ctx context.Context) ([]*model.Receipt, error) {
	return []*model.Receipt{}, nil
}

func (r *ReceiptResolver) Receipt(ctx context.Context, id string) (*model.Receipt, error) {
	return &model.Receipt{}, nil
}
