package user

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"

	"github.com/bishal-dd/receipt-generator-backend/graph/model"
	"github.com/bishal-dd/receipt-generator-backend/helper"
	"github.com/bishal-dd/receipt-generator-backend/pkg/db"
)

func (r *UserResolver) CreateUser(ctx context.Context, input model.CreateUser) (*model.User, error) {
	db := db.Init()
	me := &model.User{
		ID: input.ID,
		CreatedAt: helper.CurrentTime(),
	}
	if err := db.Create(me).Error; err != nil {
		return nil, err
	}

	return me, nil
}


func (r *UserResolver) DeleteUser(ctx context.Context, id string) (bool, error) {
    db := db.Init()
    user := &model.User{
        ID: id,
    }
    if err := db.Delete(user).Error; err != nil {
        return false, err
    }

    return true, nil
}