package user

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"

	"github.com/bishal-dd/receipt-generator-backend/graph/model"
)
type UserResolver struct{}

func (r *UserResolver) Users(ctx context.Context) ([]*model.User, error) {
	return []*model.User{}, nil
}

func (r *UserResolver) User(ctx context.Context, id string) (*model.User, error) {
	return &model.User{}, nil
}
