package user

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"

	"github.com/bishal-dd/receipt-generator-backend/graph/model"
	"github.com/bishal-dd/receipt-generator-backend/pkg/db"
)

func (r *UserResolver) CreateUser(ctx context.Context, input model.NewUser) (*model.User, error) {
	db := db.Init()
	newUser := &model.User{
		ID: input.ID,
	}
	if err := db.Create(newUser).Error; err != nil {
		// Return any error encountered during user creation
		return nil, err
	}


	// Return the created user object
	return newUser, nil
}
