// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateProfile struct {
	CompanyName    string  `json:"company_name"`
	LogoImage      *string `json:"logo_image,omitempty"`
	PhoneNo        int     `json:"phone_no"`
	Email          *string `json:"email,omitempty"`
	Address        *string `json:"address,omitempty"`
	City           *string `json:"city,omitempty"`
	Title          *string `json:"title,omitempty"`
	SignatureImage *string `json:"signature_image,omitempty"`
	UserID         string  `json:"user_id"`
}

type CreateReceipt struct {
	ReceiptName    string   `json:"receipt_name"`
	RecipientName  string   `json:"recipient_name"`
	RecipientPhone int      `json:"recipient_phone"`
	Amount         float64  `json:"amount"`
	TransactionNo  *int     `json:"transaction_no,omitempty"`
	UserID         string   `json:"user_id"`
	Date           string   `json:"date"`
	TotalAmount    *float64 `json:"total_amount,omitempty"`
}

type CreateService struct {
	Description string  `json:"description"`
	Rate        float64 `json:"rate"`
	Quantity    int     `json:"quantity"`
	Amount      int     `json:"amount"`
	ReceiptID   string  `json:"receipt_id"`
}

type CreateUser struct {
	ID string `json:"id"`
}

type CreateVersion struct {
	Mode   string `json:"mode"`
	UserID string `json:"user_id"`
}

type Mutation struct {
}

type PageInfo struct {
	HasNextPage     bool    `json:"hasNextPage"`
	HasPreviousPage bool    `json:"hasPreviousPage"`
	StartCursor     *string `json:"startCursor,omitempty"`
	EndCursor       *string `json:"endCursor,omitempty"`
}

type Profile struct {
	ID             string  `json:"id"`
	CompanyName    string  `json:"company_name"`
	LogoImage      *string `json:"logo_image,omitempty"`
	PhoneNo        int     `json:"phone_no"`
	Email          *string `json:"email,omitempty"`
	Address        *string `json:"address,omitempty"`
	City           *string `json:"city,omitempty"`
	Title          *string `json:"title,omitempty"`
	SignatureImage *string `json:"signature_image,omitempty"`
	UserID         string  `json:"user_id"`
	CreatedAt      string  `json:"created_at"`
	UpdatedAt      *string `json:"updated_at,omitempty"`
	DeletedAt      *string `json:"deleted_at,omitempty"`
}

type Query struct {
}

type Receipt struct {
	ID             string   `json:"id"`
	ReceiptName    string   `json:"receipt_name"`
	RecipientName  string   `json:"recipient_name"`
	RecipientPhone int      `json:"recipient_phone"`
	Amount         float64  `json:"amount"`
	TransactionNo  *int     `json:"transaction_no,omitempty"`
	UserID         string   `json:"user_id"`
	Date           string   `json:"date"`
	TotalAmount    *float64 `json:"total_amount,omitempty"`
	CreatedAt      string   `json:"created_at"`
	UpdatedAt      *string  `json:"updated_at,omitempty"`
	DeletedAt      *string  `json:"deleted_at,omitempty"`
}

type ReceiptConnection struct {
	Edges      []*ReceiptEdge `json:"edges"`
	PageInfo   *PageInfo      `json:"pageInfo"`
	TotalCount int            `json:"totalCount"`
}

type ReceiptEdge struct {
	Cursor string   `json:"cursor"`
	Node   *Receipt `json:"node"`
}

type Service struct {
	ID          string  `json:"id"`
	Description string  `json:"description"`
	Rate        float64 `json:"rate"`
	Quantity    int     `json:"quantity"`
	Amount      int     `json:"amount"`
	ReceiptID   string  `json:"receipt_id"`
	CreatedAt   string  `json:"created_at"`
	UpdatedAt   *string `json:"updated_at,omitempty"`
	DeletedAt   *string `json:"deleted_at,omitempty"`
}

type UpdateProfile struct {
	ID             string  `json:"id"`
	CompanyName    *string `json:"company_name,omitempty"`
	LogoImage      *string `json:"logo_image,omitempty"`
	PhoneNo        *int    `json:"phone_no,omitempty"`
	Email          *string `json:"email,omitempty"`
	Address        *string `json:"address,omitempty"`
	City           *string `json:"city,omitempty"`
	Title          *string `json:"title,omitempty"`
	SignatureImage *string `json:"signature_image,omitempty"`
}

type UpdateReceipt struct {
	ID             string   `json:"id"`
	ReceiptName    *string  `json:"receipt_name,omitempty"`
	RecipientName  *string  `json:"recipient_name,omitempty"`
	RecipientPhone *int     `json:"recipient_phone,omitempty"`
	Amount         *float64 `json:"amount,omitempty"`
	TransactionNo  *int     `json:"transaction_no,omitempty"`
	UserID         *string  `json:"user_id,omitempty"`
	Date           *string  `json:"date,omitempty"`
	TotalAmount    *float64 `json:"total_amount,omitempty"`
}

type UpdateService struct {
	ID          string   `json:"id"`
	Description *string  `json:"description,omitempty"`
	Rate        *float64 `json:"rate,omitempty"`
	Quantity    *int     `json:"quantity,omitempty"`
	Amount      *int     `json:"amount,omitempty"`
}

type UpdateVersion struct {
	ID       string  `json:"id"`
	Mode     *string `json:"mode,omitempty"`
	UserID   *string `json:"user_id,omitempty"`
	UseCount *int    `json:"use_count,omitempty"`
}

type User struct {
	ID        string     `json:"id"`
	CreatedAt string     `json:"created_at"`
	UpdatedAt *string    `json:"updated_at,omitempty"`
	DeletedAt *string    `json:"deleted_at,omitempty"`
	Receipts  []*Receipt `json:"Receipts,omitempty"`
}

type UserConnection struct {
	Edges      []*UserEdge `json:"edges"`
	PageInfo   *PageInfo   `json:"pageInfo"`
	TotalCount int         `json:"totalCount"`
}

type UserEdge struct {
	Cursor string `json:"cursor"`
	Node   *User  `json:"node"`
}

type Version struct {
	ID        string  `json:"id"`
	Mode      string  `json:"mode"`
	UserID    string  `json:"user_id"`
	UseCount  int     `json:"use_count"`
	CreatedAt string  `json:"created_at"`
	UpdatedAt *string `json:"updated_at,omitempty"`
	DeletedAt *string `json:"deleted_at,omitempty"`
}
